// Generated by Supabase CLI 2.119.0 from the actual local Supabase database.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  
  "public": {
          Tables: {
            "agent_setting_versions": {
                  Row: {
                    "created_at": string,"created_by": string,"default_model_id": string | null,"id": string,"mode": Database["public"]['Enums']["agent_mode"],"prompt_version_id": string,"version": number,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"default_model_id"?: string | null,"id"?: string,"mode"?: Database["public"]['Enums']["agent_mode"],"prompt_version_id": string,"version": number,"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"default_model_id"?: string | null,"id"?: string,"mode"?: Database["public"]['Enums']["agent_mode"],"prompt_version_id"?: string,"version"?: number,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "agent_setting_versions_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "agent_setting_versions_default_model_id_workspace_id_fkey"
      columns: ["default_model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "agent_setting_versions_prompt_version_id_workspace_id_fkey"
      columns: ["prompt_version_id","workspace_id"]
isOneToOne: false
      referencedRelation: "prompt_versions"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "agent_setting_versions_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"agent_settings": {
                  Row: {
                    "created_at": string,"created_by": string,"current_version_id": string,"id": string,"revision": number,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"current_version_id": string,"id"?: string,"revision"?: number,"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"current_version_id"?: string,"id"?: string,"revision"?: number,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "agent_settings_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "agent_settings_current_version_id_workspace_id_fkey"
      columns: ["current_version_id","workspace_id"]
isOneToOne: false
      referencedRelation: "agent_setting_versions"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "agent_settings_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: true
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"ai_models": {
                  Row: {
                    "capabilities_verified_at": string | null,"created_at": string,"created_by": string,"display_name": string,"enabled": boolean,"hosting_region": Database["public"]['Enums']["hosting_region"],"id": string,"provider": Database["public"]['Enums']["ai_provider"],"provider_model_id": string,"region_evidence_url": string | null,"status": Database["public"]['Enums']["model_status"],"supports_tools": boolean | null,"supports_vision": boolean | null,"workspace_id": string
                  }
                  Insert: {
                    "capabilities_verified_at"?: string | null,"created_at"?: string,"created_by": string,"display_name": string,"enabled"?: boolean,"hosting_region"?: Database["public"]['Enums']["hosting_region"],"id"?: string,"provider": Database["public"]['Enums']["ai_provider"],"provider_model_id": string,"region_evidence_url"?: string | null,"status"?: Database["public"]['Enums']["model_status"],"supports_tools"?: boolean | null,"supports_vision"?: boolean | null,"workspace_id": string
                  }
                  Update: {
                    "capabilities_verified_at"?: string | null,"created_at"?: string,"created_by"?: string,"display_name"?: string,"enabled"?: boolean,"hosting_region"?: Database["public"]['Enums']["hosting_region"],"id"?: string,"provider"?: Database["public"]['Enums']["ai_provider"],"provider_model_id"?: string,"region_evidence_url"?: string | null,"status"?: Database["public"]['Enums']["model_status"],"supports_tools"?: boolean | null,"supports_vision"?: boolean | null,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "ai_models_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "ai_models_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"attachments": {
                  Row: {
                    "bucket_id": string,"byte_size": number,"care_recipient_id": string | null,"conversation_id": string | null,"created_at": string,"created_by": string,"display_name": string,"id": string,"message_id": string | null,"mime_type": string,"object_path": string,"sha256": string | null,"status": Database["public"]['Enums']["attachment_status"],"visibility": Database["public"]['Enums']["attachment_scope"],"workspace_id": string
                  }
                  Insert: {
                    "bucket_id"?: string,"byte_size": number,"care_recipient_id"?: string | null,"conversation_id"?: string | null,"created_at"?: string,"created_by": string,"display_name": string,"id"?: string,"message_id"?: string | null,"mime_type": string,"object_path": string,"sha256"?: string | null,"status"?: Database["public"]['Enums']["attachment_status"],"visibility"?: Database["public"]['Enums']["attachment_scope"],"workspace_id": string
                  }
                  Update: {
                    "bucket_id"?: string,"byte_size"?: number,"care_recipient_id"?: string | null,"conversation_id"?: string | null,"created_at"?: string,"created_by"?: string,"display_name"?: string,"id"?: string,"message_id"?: string | null,"mime_type"?: string,"object_path"?: string,"sha256"?: string | null,"status"?: Database["public"]['Enums']["attachment_status"],"visibility"?: Database["public"]['Enums']["attachment_scope"],"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "attachments_care_recipient_id_workspace_id_fkey"
      columns: ["care_recipient_id","workspace_id"]
isOneToOne: false
      referencedRelation: "care_recipients"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "attachments_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "attachments_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "attachments_message_id_conversation_id_workspace_id_fkey"
      columns: ["message_id","conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id","conversation_id","workspace_id"]
    },{
      foreignKeyName: "attachments_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"audit_log": {
                  Row: {
                    "action": string,"conversation_id": string | null,"created_at": string,"created_by": string,"id": string,"message_id": string | null,"metadata": NonNullable<Json>,"model_id": string | null,"outcome": string,"request_id": string | null,"target_id": string | null,"target_table": string | null,"tool_name": string | null,"workspace_id": string
                  }
                  Insert: {
                    "action": string,"conversation_id"?: string | null,"created_at"?: string,"created_by": string,"id"?: string,"message_id"?: string | null,"metadata"?: NonNullable<Json>,"model_id"?: string | null,"outcome": string,"request_id"?: string | null,"target_id"?: string | null,"target_table"?: string | null,"tool_name"?: string | null,"workspace_id": string
                  }
                  Update: {
                    "action"?: string,"conversation_id"?: string | null,"created_at"?: string,"created_by"?: string,"id"?: string,"message_id"?: string | null,"metadata"?: NonNullable<Json>,"model_id"?: string | null,"outcome"?: string,"request_id"?: string | null,"target_id"?: string | null,"target_table"?: string | null,"tool_name"?: string | null,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "audit_log_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "audit_log_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "audit_log_message_id_conversation_id_workspace_id_fkey"
      columns: ["message_id","conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id","conversation_id","workspace_id"]
    },{
      foreignKeyName: "audit_log_model_id_workspace_id_fkey"
      columns: ["model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "audit_log_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"care_recipients": {
                  Row: {
                    "address": NonNullable<Json>,"birth_date": string | null,"care_grade": number,"created_at": string,"created_by": string,"id": string,"insurer_contact_id": string | null,"name": string,"summary": string,"workspace_id": string
                  }
                  Insert: {
                    "address"?: NonNullable<Json>,"birth_date"?: string | null,"care_grade"?: number,"created_at"?: string,"created_by": string,"id"?: string,"insurer_contact_id"?: string | null,"name": string,"summary"?: string,"workspace_id": string
                  }
                  Update: {
                    "address"?: NonNullable<Json>,"birth_date"?: string | null,"care_grade"?: number,"created_at"?: string,"created_by"?: string,"id"?: string,"insurer_contact_id"?: string | null,"name"?: string,"summary"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "care_recipients_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "care_recipients_insurer_contact_id_workspace_id_fkey"
      columns: ["insurer_contact_id","workspace_id"]
isOneToOne: false
      referencedRelation: "contacts"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "care_recipients_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"chat_requests": {
                  Row: {
                    "assistant_message_id": string,"client_request_id": string,"context_snapshot": NonNullable<Json>,"conversation_id": string,"created_at": string,"created_by": string,"id": string,"lease_expires_at": string,"model_id": string,"payload_sha256": string,"prompt_version_id": string,"reservation_id": string,"session_id": string,"status": string,"user_message_id": string,"workspace_id": string
                  }
                  Insert: {
                    "assistant_message_id": string,"client_request_id": string,"context_snapshot": NonNullable<Json>,"conversation_id": string,"created_at"?: string,"created_by": string,"id"?: string,"lease_expires_at": string,"model_id": string,"payload_sha256": string,"prompt_version_id": string,"reservation_id": string,"session_id": string,"status": string,"user_message_id": string,"workspace_id": string
                  }
                  Update: {
                    "assistant_message_id"?: string,"client_request_id"?: string,"context_snapshot"?: NonNullable<Json>,"conversation_id"?: string,"created_at"?: string,"created_by"?: string,"id"?: string,"lease_expires_at"?: string,"model_id"?: string,"payload_sha256"?: string,"prompt_version_id"?: string,"reservation_id"?: string,"session_id"?: string,"status"?: string,"user_message_id"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "chat_requests_assistant_message_id_conversation_id_workspa_fkey"
      columns: ["assistant_message_id","conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id","conversation_id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_model_id_workspace_id_fkey"
      columns: ["model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_prompt_version_id_workspace_id_fkey"
      columns: ["prompt_version_id","workspace_id"]
isOneToOne: false
      referencedRelation: "prompt_versions"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_reservation_id_workspace_id_fkey"
      columns: ["reservation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "cost_reservations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_user_message_id_conversation_id_workspace_id_fkey"
      columns: ["user_message_id","conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id","conversation_id","workspace_id"]
    },{
      foreignKeyName: "chat_requests_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"contacts": {
                  Row: {
                    "address": NonNullable<Json>,"created_at": string,"created_by": string,"email": string | null,"id": string,"kind": string,"name": string,"phone": string | null,"reference": string | null,"workspace_id": string
                  }
                  Insert: {
                    "address"?: NonNullable<Json>,"created_at"?: string,"created_by": string,"email"?: string | null,"id"?: string,"kind": string,"name": string,"phone"?: string | null,"reference"?: string | null,"workspace_id": string
                  }
                  Update: {
                    "address"?: NonNullable<Json>,"created_at"?: string,"created_by"?: string,"email"?: string | null,"id"?: string,"kind"?: string,"name"?: string,"phone"?: string | null,"reference"?: string | null,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "contacts_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "contacts_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"conversation_requests": {
                  Row: {
                    "conversation_id": string,"created_at": string,"created_by": string,"id": string,"idempotency_key": string,"payload_sha256": string,"workspace_id": string
                  }
                  Insert: {
                    "conversation_id": string,"created_at"?: string,"created_by": string,"id"?: string,"idempotency_key": string,"payload_sha256": string,"workspace_id": string
                  }
                  Update: {
                    "conversation_id"?: string,"created_at"?: string,"created_by"?: string,"id"?: string,"idempotency_key"?: string,"payload_sha256"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "conversation_requests_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "conversation_requests_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "conversation_requests_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"conversations": {
                  Row: {
                    "archived_at": string | null,"care_recipient_id": string | null,"created_at": string,"created_by": string,"id": string,"mode_override": Database["public"]['Enums']["agent_mode"] | null,"model_override_id": string | null,"revision": number,"title": string,"workspace_id": string
                  }
                  Insert: {
                    "archived_at"?: string | null,"care_recipient_id"?: string | null,"created_at"?: string,"created_by": string,"id"?: string,"mode_override"?: Database["public"]['Enums']["agent_mode"] | null,"model_override_id"?: string | null,"revision"?: number,"title": string,"workspace_id": string
                  }
                  Update: {
                    "archived_at"?: string | null,"care_recipient_id"?: string | null,"created_at"?: string,"created_by"?: string,"id"?: string,"mode_override"?: Database["public"]['Enums']["agent_mode"] | null,"model_override_id"?: string | null,"revision"?: number,"title"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "conversations_care_recipient_id_workspace_id_fkey"
      columns: ["care_recipient_id","workspace_id"]
isOneToOne: false
      referencedRelation: "care_recipients"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "conversations_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "conversations_model_override_id_workspace_id_fkey"
      columns: ["model_override_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "conversations_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"cost_reservations": {
                  Row: {
                    "amount_microusd": number,"created_at": string,"created_by": string,"id": string,"model_id": string,"month": string,"price_snapshot": NonNullable<Json>,"request_id": string,"settled_at": string | null,"status": Database["public"]['Enums']["reservation_status"],"workspace_id": string
                  }
                  Insert: {
                    "amount_microusd": number,"created_at"?: string,"created_by": string,"id"?: string,"model_id": string,"month": string,"price_snapshot": NonNullable<Json>,"request_id": string,"settled_at"?: string | null,"status"?: Database["public"]['Enums']["reservation_status"],"workspace_id": string
                  }
                  Update: {
                    "amount_microusd"?: number,"created_at"?: string,"created_by"?: string,"id"?: string,"model_id"?: string,"month"?: string,"price_snapshot"?: NonNullable<Json>,"request_id"?: string,"settled_at"?: string | null,"status"?: Database["public"]['Enums']["reservation_status"],"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "cost_reservations_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "cost_reservations_model_id_workspace_id_fkey"
      columns: ["model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "cost_reservations_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"document_versions": {
                  Row: {
                    "content": NonNullable<Json>,"created_at": string,"created_by": string,"document_id": string,"id": string,"rendered_text": string,"version": number,"workspace_id": string
                  }
                  Insert: {
                    "content": NonNullable<Json>,"created_at"?: string,"created_by": string,"document_id": string,"id"?: string,"rendered_text": string,"version": number,"workspace_id": string
                  }
                  Update: {
                    "content"?: NonNullable<Json>,"created_at"?: string,"created_by"?: string,"document_id"?: string,"id"?: string,"rendered_text"?: string,"version"?: number,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "document_versions_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "document_versions_document_id_workspace_id_fkey"
      columns: ["document_id","workspace_id"]
isOneToOne: false
      referencedRelation: "documents"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "document_versions_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"documents": {
                  Row: {
                    "care_recipient_id": string | null,"content": NonNullable<Json>,"conversation_id": string | null,"created_at": string,"created_by": string,"id": string,"kind": Database["public"]['Enums']["document_kind"],"rendered_text": string,"revision": number,"status": Database["public"]['Enums']["document_status"],"title": string,"workspace_id": string
                  }
                  Insert: {
                    "care_recipient_id"?: string | null,"content": NonNullable<Json>,"conversation_id"?: string | null,"created_at"?: string,"created_by": string,"id"?: string,"kind": Database["public"]['Enums']["document_kind"],"rendered_text": string,"revision"?: number,"status"?: Database["public"]['Enums']["document_status"],"title": string,"workspace_id": string
                  }
                  Update: {
                    "care_recipient_id"?: string | null,"content"?: NonNullable<Json>,"conversation_id"?: string | null,"created_at"?: string,"created_by"?: string,"id"?: string,"kind"?: Database["public"]['Enums']["document_kind"],"rendered_text"?: string,"revision"?: number,"status"?: Database["public"]['Enums']["document_status"],"title"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "documents_care_recipient_id_workspace_id_fkey"
      columns: ["care_recipient_id","workspace_id"]
isOneToOne: false
      referencedRelation: "care_recipients"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "documents_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "documents_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "documents_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"messages": {
                  Row: {
                    "client_request_id": string | null,"content": string,"conversation_id": string,"created_at": string,"created_by": string,"id": string,"input_tokens": number | null,"model_id": string | null,"model_snapshot": Json | null,"output_tokens": number | null,"prompt_version_id": string | null,"provider_response_model": string | null,"role": Database["public"]['Enums']["message_role"],"sources": NonNullable<Json>,"status": Database["public"]['Enums']["message_status"],"tool_calls": NonNullable<Json>,"workspace_id": string
                  }
                  Insert: {
                    "client_request_id"?: string | null,"content"?: string,"conversation_id": string,"created_at"?: string,"created_by": string,"id"?: string,"input_tokens"?: number | null,"model_id"?: string | null,"model_snapshot"?: Json | null,"output_tokens"?: number | null,"prompt_version_id"?: string | null,"provider_response_model"?: string | null,"role": Database["public"]['Enums']["message_role"],"sources"?: NonNullable<Json>,"status"?: Database["public"]['Enums']["message_status"],"tool_calls"?: NonNullable<Json>,"workspace_id": string
                  }
                  Update: {
                    "client_request_id"?: string | null,"content"?: string,"conversation_id"?: string,"created_at"?: string,"created_by"?: string,"id"?: string,"input_tokens"?: number | null,"model_id"?: string | null,"model_snapshot"?: Json | null,"output_tokens"?: number | null,"prompt_version_id"?: string | null,"provider_response_model"?: string | null,"role"?: Database["public"]['Enums']["message_role"],"sources"?: NonNullable<Json>,"status"?: Database["public"]['Enums']["message_status"],"tool_calls"?: NonNullable<Json>,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "messages_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "messages_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "messages_model_id_workspace_id_fkey"
      columns: ["model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "messages_prompt_version_id_workspace_id_fkey"
      columns: ["prompt_version_id","workspace_id"]
isOneToOne: false
      referencedRelation: "prompt_versions"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "messages_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"model_prices": {
                  Row: {
                    "created_at": string,"created_by": string,"currency": string,"evidence_url": string,"expires_at": string,"id": string,"input_microusd_per_million": number,"model_id": string,"output_microusd_per_million": number,"text_only": boolean,"verified_at": string,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"currency"?: string,"evidence_url": string,"expires_at": string,"id"?: string,"input_microusd_per_million": number,"model_id": string,"output_microusd_per_million": number,"text_only"?: boolean,"verified_at": string,"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"currency"?: string,"evidence_url"?: string,"expires_at"?: string,"id"?: string,"input_microusd_per_million"?: number,"model_id"?: string,"output_microusd_per_million"?: number,"text_only"?: boolean,"verified_at"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "model_prices_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "model_prices_model_id_workspace_id_fkey"
      columns: ["model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "model_prices_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"notes": {
                  Row: {
                    "body": string,"care_recipient_id": string,"conversation_id": string | null,"created_at": string,"created_by": string,"id": string,"workspace_id": string
                  }
                  Insert: {
                    "body": string,"care_recipient_id": string,"conversation_id"?: string | null,"created_at"?: string,"created_by": string,"id"?: string,"workspace_id": string
                  }
                  Update: {
                    "body"?: string,"care_recipient_id"?: string,"conversation_id"?: string | null,"created_at"?: string,"created_by"?: string,"id"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "notes_care_recipient_id_workspace_id_fkey"
      columns: ["care_recipient_id","workspace_id"]
isOneToOne: false
      referencedRelation: "care_recipients"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "notes_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "notes_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "notes_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"profiles": {
                  Row: {
                    "created_at": string,"created_by": string,"display_name": string,"id": string,"kind": Database["public"]['Enums']["actor_kind"],"user_id": string | null,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"display_name": string,"id"?: string,"kind": Database["public"]['Enums']["actor_kind"],"user_id"?: string | null,"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"display_name"?: string,"id"?: string,"kind"?: Database["public"]['Enums']["actor_kind"],"user_id"?: string | null,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "profiles_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "profiles_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"prompt_versions": {
                  Row: {
                    "created_at": string,"created_by": string,"id": string,"is_default": boolean,"persona": string,"system_prompt": string,"version": number,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"id"?: string,"is_default"?: boolean,"persona": string,"system_prompt": string,"version": number,"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"id"?: string,"is_default"?: boolean,"persona"?: string,"system_prompt"?: string,"version"?: number,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "prompt_versions_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "prompt_versions_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"session_activity": {
                  Row: {
                    "created_at": string,"created_by": string,"expires_at": string,"id": string,"last_interaction_at": string,"remember_session": boolean,"revoked_at": string | null,"session_id": string,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"expires_at": string,"id"?: string,"last_interaction_at": string,"remember_session"?: boolean,"revoked_at"?: string | null,"session_id": string,"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"expires_at"?: string,"id"?: string,"last_interaction_at"?: string,"remember_session"?: boolean,"revoked_at"?: string | null,"session_id"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "session_activity_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "session_activity_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"tasks": {
                  Row: {
                    "care_recipient_id": string | null,"conversation_id": string | null,"created_at": string,"created_by": string,"deadline_source": string | null,"description": string,"due_at": string | null,"id": string,"kind": string,"priority": Database["public"]['Enums']["task_priority"],"status": Database["public"]['Enums']["task_status"],"title": string,"workspace_id": string
                  }
                  Insert: {
                    "care_recipient_id"?: string | null,"conversation_id"?: string | null,"created_at"?: string,"created_by": string,"deadline_source"?: string | null,"description"?: string,"due_at"?: string | null,"id"?: string,"kind"?: string,"priority"?: Database["public"]['Enums']["task_priority"],"status"?: Database["public"]['Enums']["task_status"],"title": string,"workspace_id": string
                  }
                  Update: {
                    "care_recipient_id"?: string | null,"conversation_id"?: string | null,"created_at"?: string,"created_by"?: string,"deadline_source"?: string | null,"description"?: string,"due_at"?: string | null,"id"?: string,"kind"?: string,"priority"?: Database["public"]['Enums']["task_priority"],"status"?: Database["public"]['Enums']["task_status"],"title"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "tasks_care_recipient_id_workspace_id_fkey"
      columns: ["care_recipient_id","workspace_id"]
isOneToOne: false
      referencedRelation: "care_recipients"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "tasks_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "tasks_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "tasks_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"tool_proposals": {
                  Row: {
                    "confirmed_at": string | null,"confirmed_preview": Json | null,"context_sha256": string,"conversation_id": string,"created_at": string,"created_by": string,"expires_at": string,"id": string,"idempotency_key": string | null,"kind": Database["public"]['Enums']["proposal_kind"],"message_id": string,"payload_sha256": string | null,"preview": NonNullable<Json>,"result_id": string | null,"revision": number,"snapshot": NonNullable<Json>,"status": Database["public"]['Enums']["proposal_status"],"workspace_id": string
                  }
                  Insert: {
                    "confirmed_at"?: string | null,"confirmed_preview"?: Json | null,"context_sha256": string,"conversation_id": string,"created_at"?: string,"created_by": string,"expires_at": string,"id"?: string,"idempotency_key"?: string | null,"kind": Database["public"]['Enums']["proposal_kind"],"message_id": string,"payload_sha256"?: string | null,"preview": NonNullable<Json>,"result_id"?: string | null,"revision"?: number,"snapshot": NonNullable<Json>,"status"?: Database["public"]['Enums']["proposal_status"],"workspace_id": string
                  }
                  Update: {
                    "confirmed_at"?: string | null,"confirmed_preview"?: Json | null,"context_sha256"?: string,"conversation_id"?: string,"created_at"?: string,"created_by"?: string,"expires_at"?: string,"id"?: string,"idempotency_key"?: string | null,"kind"?: Database["public"]['Enums']["proposal_kind"],"message_id"?: string,"payload_sha256"?: string | null,"preview"?: NonNullable<Json>,"result_id"?: string | null,"revision"?: number,"snapshot"?: NonNullable<Json>,"status"?: Database["public"]['Enums']["proposal_status"],"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "tool_proposals_conversation_id_workspace_id_fkey"
      columns: ["conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "conversations"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "tool_proposals_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "tool_proposals_message_id_conversation_id_workspace_id_fkey"
      columns: ["message_id","conversation_id","workspace_id"]
isOneToOne: false
      referencedRelation: "messages"
      referencedColumns: ["id","conversation_id","workspace_id"]
    },{
      foreignKeyName: "tool_proposals_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"usage_ledger": {
                  Row: {
                    "cached_tokens": number,"cost_microusd": number,"created_at": string,"created_by": string,"estimated": boolean,"id": string,"input_tokens": number,"model_id": string,"month": string,"output_tokens": number,"request_id": string,"reservation_id": string,"workspace_id": string
                  }
                  Insert: {
                    "cached_tokens"?: number,"cost_microusd": number,"created_at"?: string,"created_by": string,"estimated"?: boolean,"id"?: string,"input_tokens": number,"model_id": string,"month": string,"output_tokens": number,"request_id": string,"reservation_id": string,"workspace_id": string
                  }
                  Update: {
                    "cached_tokens"?: number,"cost_microusd"?: number,"created_at"?: string,"created_by"?: string,"estimated"?: boolean,"id"?: string,"input_tokens"?: number,"model_id"?: string,"month"?: string,"output_tokens"?: number,"request_id"?: string,"reservation_id"?: string,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "usage_ledger_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "usage_ledger_model_id_workspace_id_fkey"
      columns: ["model_id","workspace_id"]
isOneToOne: false
      referencedRelation: "ai_models"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "usage_ledger_reservation_id_workspace_id_model_id_request__fkey"
      columns: ["reservation_id","workspace_id","model_id","request_id","month"]
isOneToOne: false
      referencedRelation: "cost_reservations"
      referencedColumns: ["id","workspace_id","model_id","request_id","month"]
    },{
      foreignKeyName: "usage_ledger_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"workspace_budgets": {
                  Row: {
                    "blocked": boolean,"created_at": string,"created_by": string,"currency": string,"id": string,"monthly_cap_microusd": number | null,"total_cap_microusd": number | null,"workspace_id": string
                  }
                  Insert: {
                    "blocked"?: boolean,"created_at"?: string,"created_by": string,"currency"?: string,"id"?: string,"monthly_cap_microusd"?: number | null,"total_cap_microusd"?: number | null,"workspace_id": string
                  }
                  Update: {
                    "blocked"?: boolean,"created_at"?: string,"created_by"?: string,"currency"?: string,"id"?: string,"monthly_cap_microusd"?: number | null,"total_cap_microusd"?: number | null,"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "workspace_budgets_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "workspace_budgets_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: true
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"workspace_memberships": {
                  Row: {
                    "created_at": string,"created_by": string,"id": string,"profile_id": string,"role": Database["public"]['Enums']["membership_role"],"status": Database["public"]['Enums']["membership_status"],"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"id"?: string,"profile_id": string,"role"?: Database["public"]['Enums']["membership_role"],"status"?: Database["public"]['Enums']["membership_status"],"workspace_id": string
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"id"?: string,"profile_id"?: string,"role"?: Database["public"]['Enums']["membership_role"],"status"?: Database["public"]['Enums']["membership_status"],"workspace_id"?: string
                  }
                  Relationships: [
                    {
      foreignKeyName: "workspace_memberships_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "workspace_memberships_profile_id_workspace_id_fkey"
      columns: ["profile_id","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    },{
      foreignKeyName: "workspace_memberships_workspace_id_fkey"
      columns: ["workspace_id"]
isOneToOne: false
      referencedRelation: "workspaces"
      referencedColumns: ["id"]
    }
                  ]
                },"workspaces": {
                  Row: {
                    "created_at": string,"created_by": string,"demo_banner": boolean,"id": string,"name": string,"workspace_id": string
                  }
                  Insert: {
                    "created_at"?: string,"created_by": string,"demo_banner"?: boolean,"id"?: string,"name": string,"workspace_id"?: never
                  }
                  Update: {
                    "created_at"?: string,"created_by"?: string,"demo_banner"?: boolean,"id"?: string,"name"?: string,"workspace_id"?: never
                  }
                  Relationships: [
                    {
      foreignKeyName: "workspaces_created_by_workspace_id_fkey"
      columns: ["created_by","workspace_id"]
isOneToOne: false
      referencedRelation: "profiles"
      referencedColumns: ["id","workspace_id"]
    }
                  ]
                }
          }
          Views: {
            [_ in never]: never
          }
          Functions: {
            "assign_conversation_recipient":
{ Args: { "p_care_recipient_id": string,"p_conversation_id": string,"p_expected_revision": number }; Returns: {
              "archived_at": string | null,
"care_recipient_id": string | null,
"created_at": string,
"created_by": string,
"id": string,
"mode_override": Database["public"]['Enums']["agent_mode"] | null,
"model_override_id": string | null,
"revision": number,
"title": string,
"workspace_id": string
            }
                          SetofOptions: {
        from: "*"
        to: "conversations"
        isOneToOne: true
        isSetofReturn: false
      } },
"create_conversation":
{ Args: { "p_care_recipient_id": string,"p_idempotency_key": string,"p_title": string,"p_workspace_id": string }; Returns: {
              "archived_at": string | null,
"care_recipient_id": string | null,
"created_at": string,
"created_by": string,
"id": string,
"mode_override": Database["public"]['Enums']["agent_mode"] | null,
"model_override_id": string | null,
"revision": number,
"title": string,
"workspace_id": string
            }
                          SetofOptions: {
        from: "*"
        to: "conversations"
        isOneToOne: true
        isSetofReturn: false
      } },
"edge_chat_check":
{ Args: { "p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: boolean
                           },
"edge_chat_checkpoint":
{ Args: { "p_content": string,"p_request_id": string,"p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: boolean
                           },
"edge_chat_finish":
{ Args: { "p_content": string,"p_input_tokens": number,"p_output_tokens": number,"p_request_id": string,"p_response_model": string,"p_status": string,"p_user_id": string,"p_workspace_id": string }; Returns: Json
                           },
"edge_chat_prepare":
{ Args: { "p_content": string,"p_conversation_id": string,"p_request_id": string,"p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: Json
                           },
"edge_chat_reap":
{ Args: { "p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: number
                           },
"edge_chat_replay":
{ Args: { "p_content": string,"p_conversation_id": string,"p_request_id": string,"p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: Json
                           },
"edge_session":
{ Args: { "p_action": string,"p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: Json
                           } |
{ Args: { "p_action": string,"p_remember_session": boolean,"p_session_id": string,"p_user_id": string,"p_workspace_id": string }; Returns: Json
                           },
"mark_document_status":
{ Args: { "p_document_id": string,"p_expected_revision": number,"p_status": Database["public"]['Enums']["document_status"] }; Returns: {
              "care_recipient_id": string | null,
"content": NonNullable<Json>,
"conversation_id": string | null,
"created_at": string,
"created_by": string,
"id": string,
"kind": Database["public"]['Enums']["document_kind"],
"rendered_text": string,
"revision": number,
"status": Database["public"]['Enums']["document_status"],
"title": string,
"workspace_id": string
            }
                          SetofOptions: {
        from: "*"
        to: "documents"
        isOneToOne: true
        isSetofReturn: false
      } },
"rename_conversation":
{ Args: { "p_conversation_id": string,"p_expected_revision": number,"p_title": string }; Returns: {
              "archived_at": string | null,
"care_recipient_id": string | null,
"created_at": string,
"created_by": string,
"id": string,
"mode_override": Database["public"]['Enums']["agent_mode"] | null,
"model_override_id": string | null,
"revision": number,
"title": string,
"workspace_id": string
            }
                          SetofOptions: {
        from: "*"
        to: "conversations"
        isOneToOne: true
        isSetofReturn: false
      } },
"set_conversation_preferences":
{ Args: { "p_archived": boolean,"p_conversation_id": string,"p_expected_revision": number,"p_mode": Database["public"]['Enums']["agent_mode"],"p_model_id": string }; Returns: {
              "archived_at": string | null,
"care_recipient_id": string | null,
"created_at": string,
"created_by": string,
"id": string,
"mode_override": Database["public"]['Enums']["agent_mode"] | null,
"model_override_id": string | null,
"revision": number,
"title": string,
"workspace_id": string
            }
                          SetofOptions: {
        from: "*"
        to: "conversations"
        isOneToOne: true
        isSetofReturn: false
      } },
"staff_overview":
{ Args: { "p_workspace_id": string }; Returns: Json
                           },
"update_agent_settings":
{ Args: { "p_expected_revision": number,"p_mode": Database["public"]['Enums']["agent_mode"],"p_model_id": string,"p_persona": string,"p_reset_to_default": boolean,"p_system_prompt": string,"p_workspace_id": string }; Returns: {
              "created_at": string,
"created_by": string,
"current_version_id": string,
"id": string,
"revision": number,
"workspace_id": string
            }
                          SetofOptions: {
        from: "*"
        to: "agent_settings"
        isOneToOne: true
        isSetofReturn: false
      } }
          }
          Enums: {
            "actor_kind": "system"|"user","agent_mode": "answer_only"|"create","ai_provider": "openai"|"anthropic"|"mistral"|"deepseek"|"opencode"|"gemini","attachment_scope": "workspace"|"owner","attachment_status": "pending"|"ready"|"rejected"|"deleted","document_kind": "letter"|"application"|"objection"|"respite"|"relief","document_status": "draft"|"reviewed"|"sent","hosting_region": "eu"|"us"|"unverified","membership_role": "member"|"admin","membership_status": "active"|"revoked","message_role": "user"|"assistant"|"system"|"tool","message_status": "pending"|"streaming"|"completed"|"interrupted"|"failed","model_status": "planned"|"operational"|"retired","proposal_kind": "document"|"task"|"note"|"handover","proposal_status": "pending"|"confirmed"|"rejected"|"expired"|"stale","reservation_status": "reserved"|"settled"|"held"|"released","task_priority": "low"|"normal"|"high"|"urgent","task_status": "open"|"in_progress"|"done"|"cancelled"
          }
          CompositeTypes: {
            [_ in never]: never
          }
        }
}

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
  ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
      Row: infer R
    }
    ? R
    : never
  : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Insert: infer I
    }
    ? I
    : never
  : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = DefaultSchemaTableNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
  ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
      Update: infer U
    }
    ? U
    : never
  : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
  ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
  : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never
> = PublicCompositeTypeNameOrOptions extends { schema: keyof DatabaseWithoutInternals }
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
  ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
  : never

export const Constants = {
  "public": {
          Enums: {
            "actor_kind": ["system", "user"],"agent_mode": ["answer_only", "create"],"ai_provider": ["openai", "anthropic", "mistral", "deepseek", "opencode", "gemini"],"attachment_scope": ["workspace", "owner"],"attachment_status": ["pending", "ready", "rejected", "deleted"],"document_kind": ["letter", "application", "objection", "respite", "relief"],"document_status": ["draft", "reviewed", "sent"],"hosting_region": ["eu", "us", "unverified"],"membership_role": ["member", "admin"],"membership_status": ["active", "revoked"],"message_role": ["user", "assistant", "system", "tool"],"message_status": ["pending", "streaming", "completed", "interrupted", "failed"],"model_status": ["planned", "operational", "retired"],"proposal_kind": ["document", "task", "note", "handover"],"proposal_status": ["pending", "confirmed", "rejected", "expired", "stale"],"reservation_status": ["reserved", "settled", "held", "released"],"task_priority": ["low", "normal", "high", "urgent"],"task_status": ["open", "in_progress", "done", "cancelled"]
          }
        }
} as const
