import { OPENUI_CATALOG_VERSION, OPENUI_SOURCE_LIMIT, type ChatPresentation } from '../../../types/openui';

/** Stored JSON and SSE values are untrusted even when generated by our own model. */
export function readPresentation(value: unknown): ChatPresentation | null {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) return null;
  const fields = value as Record<string, unknown>;
  if (fields.format !== 'openui' || fields.catalogVersion !== OPENUI_CATALOG_VERSION ||
    typeof fields.source !== 'string' || fields.source.length > OPENUI_SOURCE_LIMIT ||
    (fields.state !== 'streaming' && fields.state !== 'valid' && fields.state !== 'invalid' && fields.state !== 'interrupted')) return null;
  return { format: 'openui', catalogVersion: OPENUI_CATALOG_VERSION, source: fields.source, state: fields.state };
}
